name: coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
        php: [ 8.1 ]
        laravel: [ 9.* ]
        stability: [ prefer-stable ]
        include:
          - laravel: 9.*
            testbench: 7.*

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: pcov

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Run coverage
        run: |
          echo "::echo::on"
          rm -f ./database/database.sqlite
          touch ./database/database.sqlite
          echo $(which grep)
          echo $(which tr)
          COVERAGE=$(vendor/bin/pest --coverage --colors=never | grep 'Cov:' | tr -d '[:blank:]' | tr -d 'Cov:' | tr -d '%')
          echo "COVERAGE=${COVERAGE}" >> $GITHUB_ENV

          if [[ $(echo "$COVERAGE < 40" | bc) -eq 1 ]]; then
            echo "BADGE_COLOR=red" >> $GITHUB_ENV
          elif [[ $(echo "$COVERAGE < 80" | bc) -eq 1 ]]; then
            echo "BADGE_COLOR=yellow" >> $GITHUB_ENV
          else
            echo "BADGE_COLOR=#30C251" >> $GITHUB_ENV
          fi
      - name: Create coverage badge
        uses: schneegans/dynamic-badges-action@v1.2.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: 45584b0dc38ce224d546245721105bdf
          filename: laravel_wallet_package-${{ github.ref_name }}.json
          label: Coverage
          message: ${{ env.COVERAGE }}%
          color: ${{ env.BADGE_COLOR }}
